import fs from "node:fs/promises";
import { createReadStream } from "node:fs";
import readline from "node:readline";
import path from "node:path";
import { writeCsv } from "../report/csv.js";
import { writeSummary } from "../report/summary.js";
import {
  writeLargestFiles,
  writeFlaggedFilenames,
  writeDuplicateHashes,
  writePdfImageOnly,
} from "../report/flagged.js";
import { writeHtml } from "../report/html.js";
import { FILECAP_VERSION } from "../version.js";

const README_TEMPLATE = `filecap audit deliverable — README
==================================

This folder is the deliverable for an accessibility audit. It describes the
files that may need remediation on a single server (or across a fleet of
servers if this is a consolidated report).

What's in this folder:

  audit-file-list.csv      The complete file inventory, one row per file.
                           Open in Excel, Numbers, or Google Sheets. The
                           "Server", "Server IP", and "Full file path on
                           server" columns tell you exactly where to find
                           each file via SSH.

  audit-file-list.html     (only present if --html or "yes" was answered)
                           Same data as the CSV but rendered as an
                           interactive HTML page. Open in any browser.
                           Sortable columns, search box, color-coded rows
                           for image-only PDFs and flagged filenames.
                           Self-contained — no internet required.

  audit-summary.txt        Plain-text summary of the audit numbers — file
                           counts by type, PDFs that may need OCR, DOCX
                           heading coverage, etc. Suitable for a
                           manager-level overview.

  largest_files.txt        Top 50 files by size.
  flagged_filenames.txt    Files with name patterns suggesting scanned
                           origin or other a11y triage signals.
  duplicate_hashes.txt     Files with identical content (by SHA-256).
                           Vendors should remediate one copy and ignore
                           the duplicates.
  pdf_image_only.txt       PDFs that are pure scanned images (may need
                           OCR before they can be remediated).

How to find a file:

  Each row in audit-file-list.csv has "Server IP" and "Full file path on
  server" columns. To open or download a flagged file:

    ssh <user>@<server-ip>
    cd <source folder>
    cat <file name>

What "May need remediation" means:

  A file marked Yes may need a structural accessibility audit (alt text,
  heading hierarchy, table headers, tagged PDF structure, etc.). A file
  marked No is either a placeholder, an image (whose alt text lives
  elsewhere in the CMS), or a binary that may require manual review.

Generated by @icjia/filecap v__VERSION__.
For more details: https://github.com/ICJIA/filecap-cli
`;

/**
 * Orchestrate the report generation: read the inventory NDJSON line-by-line,
 * collect header/entries/footer, then write all output artifacts.
 *
 * @param {object} args
 * @param {string} args.input - path to inventory NDJSON
 * @param {string} args.outputDir - directory to write reports into (created if missing)
 * @returns {Promise<{exitCode: number, error?: string}>}
 */
export async function runReport({ input, outputDir, html = false, backHref = null, csvHref, siteUrl = null, siteFullName = null, accessKind = null, pathPrefix = null, publicUrlBaseOverride = null, sitemapUrls = [], cmsPages = [], resolveFleetFile = null, pageRefFiles = null, currentSiteName = null, siteSlug = null, fileA11yTrend = null, siteAudit = null, pageScores = null }) {
  let header;
  const entries = [];

  let stream;
  try {
    await fs.access(input);
    stream = createReadStream(input, { encoding: "utf8" });
  } catch (err) {
    return { exitCode: 2, error: `cannot read ${input}: ${err.message}` };
  }

  const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });
  for await (const line of rl) {
    if (line.length === 0) continue;
    let parsed;
    try {
      parsed = JSON.parse(line);
    } catch {
      continue;
    }
    if (parsed.kind === "filecap-inventory-header" || parsed.kind === "filecap-consolidated-header") {
      header = parsed;
    } else if (parsed.kind === "filecap-inventory-footer" || parsed.kind === "filecap-consolidated-footer") {
      // footer encountered; nothing to do here (we already collected what we need)
    } else {
      entries.push(parsed);
    }
  }

  if (!header) {
    return { exitCode: 2, error: `${input} is missing a header — partial or malformed` };
  }

  // v1.12.2: web-rollup passes the site's pathPrefix (from sites.json); the
  // scanned inventory header doesn't carry it. Inject it so buildPublicUrl
  // (csv.js + html.js) can prefix git-site URLs (e.g. the /static deploys).
  if (pathPrefix !== null && pathPrefix !== undefined && header.metadata) {
    header.metadata.pathPrefix = pathPrefix;
  }

  // v1.39.0: web-rollup resolves the live base from sites.json; the base
  // cached in the scanned header can be stale (site moved hosts). Injected
  // the same way as pathPrefix so buildPublicUrl picks it up for every
  // CSV/HTML/XLSX row.
  if (publicUrlBaseOverride !== null && publicUrlBaseOverride !== undefined && header.metadata) {
    header.metadata.publicUrlBase = publicUrlBaseOverride;
  }

  await fs.mkdir(outputDir, { recursive: true });

  const isConsolidated = header.kind === "filecap-consolidated-header";
  const sources = isConsolidated ? header.metadata.sources : null;

  const csv = writeCsv({ sourceHeader: header, entries, sources });
  await fs.writeFile(path.join(outputDir, "audit-file-list.csv"), csv);

  const summary = writeSummary({ entries, sources, header });
  await fs.writeFile(path.join(outputDir, "audit-summary.txt"), summary);

  await fs.writeFile(path.join(outputDir, "largest_files.txt"), writeLargestFiles({ entries }));
  await fs.writeFile(path.join(outputDir, "flagged_filenames.txt"), writeFlaggedFilenames({ entries }));
  await fs.writeFile(path.join(outputDir, "duplicate_hashes.txt"), writeDuplicateHashes({ entries }));
  await fs.writeFile(path.join(outputDir, "pdf_image_only.txt"), writePdfImageOnly({ entries }));

  const readmeContent = README_TEMPLATE.replace("__VERSION__", FILECAP_VERSION);
  await fs.writeFile(path.join(outputDir, "README.txt"), readmeContent);

  if (html) {
    await writeHtml({
      sourceHeader: header,
      entries,
      sources,
      outputPath: path.join(outputDir, "audit-file-list.html"),
      backHref,
      // Default the CSV link to the sibling CSV file we just wrote — but
      // only when the caller didn't say otherwise. Web-rollup overrides with
      // the workbook filename (e.g. "dvfr-….xlsx"), or passes an explicit
      // null when there is no workbook, which must survive to writeHtml so
      // the download button is omitted (Interface Contract 6).
      csvHref: csvHref === undefined ? "audit-file-list.csv" : csvHref,
      // Web-rollup passes the site's front-end homepage URL here so the
      // meta-grid "Public URL" row shows the site (not the file server).
      siteUrl,
      // Manager-friendly title from sites.json (e.g. "Domestic Violence
      // Fatality Review"). Falls back to siteName in the h1 when null.
      siteFullName,
      // "strapi" | "github" | "server" — drives the "How to access this
      // site's files" panel near the top of the per-site report. Null when
      // the report is generated outside of web-rollup (panel is skipped).
      accessKind,
      // v1.14.0: page URLs from the site's sitemap.xml, merged into the
      // Page view so it lists every page, not just file-linking ones.
      sitemapUrls,
      // v1.14.x: the site's full CMS page list (every content entry's page),
      // merged into the Page view alongside the sitemap.
      cmsPages,
      // v1.32.0 — passed through from web-rollup so the Page view can resolve
      // CMS-hosted files a page links to their owning fleet site. Null in the
      // standalone `report` command (no fleet context) → no cross-site group.
      resolveFleetFile,
      pageRefFiles,
      currentSiteName,
      // v1.36.0 — site `name` slug (e.g. "archive-prod"), threaded so the
      // detail-page file-accessibility banner can exclude the archive.
      siteSlug,
      // v1.38.0 — "since last audit" trend ({delta, dir, sinceText}) for the banner.
      fileA11yTrend,
      siteAudit,
      pageScores,
    });
  }

  return { exitCode: 0 };
}
