import fs from "node:fs/promises";
import { createReadStream } from "node:fs";
import readline from "node:readline";
import path from "node:path";
import { writeCsv } from "../report/csv.js";
import { writeSummary } from "../report/summary.js";
import {
  writeLargestFiles,
  writeFlaggedFilenames,
  writeDuplicateHashes,
  writePdfImageOnly,
} from "../report/flagged.js";
import { writeHtml } from "../report/html.js";
import { FILECAP_VERSION } from "../version.js";

const README_TEMPLATE = `filecap audit deliverable — README
==================================

This folder is the deliverable for an accessibility audit. It describes the
files needing remediation on a single server (or across a fleet of servers if
this is a consolidated report).

What's in this folder:

  audit-file-list.csv      The complete file inventory, one row per file.
                           Open in Excel, Numbers, or Google Sheets. The
                           "Server", "Server IP", and "Full file path on
                           server" columns tell you exactly where to find
                           each file via SSH.

  audit-file-list.html     (only present if --html or "yes" was answered)
                           Same data as the CSV but rendered as an
                           interactive HTML page. Open in any browser.
                           Sortable columns, search box, color-coded rows
                           for image-only PDFs and flagged filenames.
                           Self-contained — no internet required.

  audit-summary.txt        Plain-text summary of the audit numbers — file
                           counts by type, PDFs needing OCR, DOCX heading
                           coverage, etc. Suitable for a manager-level
                           overview.

  largest_files.txt        Top 50 files by size.
  flagged_filenames.txt    Files with name patterns suggesting scanned
                           origin or other a11y triage signals.
  duplicate_hashes.txt     Files with identical content (by SHA-256).
                           Vendors should remediate one copy and ignore
                           the duplicates.
  pdf_image_only.txt       PDFs that are pure scanned images (need OCR
                           before they can be remediated).

How to find a file:

  Each row in audit-file-list.csv has "Server IP" and "Full file path on
  server" columns. To open or download a flagged file:

    ssh <user>@<server-ip>
    cd <source folder>
    cat <file name>

What "Needs remediation" means:

  A file marked Yes needs structural accessibility work (alt text, heading
  hierarchy, table headers, tagged PDF structure, etc.). A file marked No
  is either a placeholder, an image (whose alt text lives elsewhere in the
  CMS), or a binary that requires manual review.

Generated by @icjia/filecap v__VERSION__.
For more details: https://github.com/ICJIA/filecap-cli
`;

/**
 * Orchestrate the report generation: read the inventory NDJSON line-by-line,
 * collect header/entries/footer, then write all output artifacts.
 *
 * @param {object} args
 * @param {string} args.input - path to inventory NDJSON
 * @param {string} args.outputDir - directory to write reports into (created if missing)
 * @returns {Promise<{exitCode: number, error?: string}>}
 */
export async function runReport({ input, outputDir, html = false }) {
  let header;
  const entries = [];

  let stream;
  try {
    await fs.access(input);
    stream = createReadStream(input, { encoding: "utf8" });
  } catch (err) {
    return { exitCode: 2, error: `cannot read ${input}: ${err.message}` };
  }

  const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });
  for await (const line of rl) {
    if (line.length === 0) continue;
    let parsed;
    try {
      parsed = JSON.parse(line);
    } catch {
      continue;
    }
    if (parsed.kind === "filecap-inventory-header" || parsed.kind === "filecap-consolidated-header") {
      header = parsed;
    } else if (parsed.kind === "filecap-inventory-footer" || parsed.kind === "filecap-consolidated-footer") {
      // footer encountered; nothing to do here (we already collected what we need)
    } else {
      entries.push(parsed);
    }
  }

  if (!header) {
    return { exitCode: 2, error: `${input} is missing a header — partial or malformed` };
  }

  await fs.mkdir(outputDir, { recursive: true });

  const isConsolidated = header.kind === "filecap-consolidated-header";
  const sources = isConsolidated ? header.metadata.sources : null;

  const csv = writeCsv({ sourceHeader: header, entries, sources });
  await fs.writeFile(path.join(outputDir, "audit-file-list.csv"), csv);

  const summary = writeSummary({ entries, sources, header });
  await fs.writeFile(path.join(outputDir, "audit-summary.txt"), summary);

  await fs.writeFile(path.join(outputDir, "largest_files.txt"), writeLargestFiles({ entries }));
  await fs.writeFile(path.join(outputDir, "flagged_filenames.txt"), writeFlaggedFilenames({ entries }));
  await fs.writeFile(path.join(outputDir, "duplicate_hashes.txt"), writeDuplicateHashes({ entries }));
  await fs.writeFile(path.join(outputDir, "pdf_image_only.txt"), writePdfImageOnly({ entries }));

  const readmeContent = README_TEMPLATE.replace("__VERSION__", FILECAP_VERSION);
  await fs.writeFile(path.join(outputDir, "README.txt"), readmeContent);

  if (html) {
    await writeHtml({
      sourceHeader: header,
      entries,
      sources,
      outputPath: path.join(outputDir, "audit-file-list.html"),
    });
  }

  return { exitCode: 0 };
}
