export function generateNetlifyToml() {
  return `[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*.csv"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Disposition = "attachment"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"

# v1.19.0 — X-Robots-Tag applies to /* (not just /*.html) so the CSVs, the
# consolidated NDJSON, and the context .md are noindex too. This bundle is
# internal-only; nothing in it should be indexed. robots.txt already
# Disallows everything, but the header is the directive that search engines
# ignoring robots.txt still honor.
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
`;
}

/**
 * v1.7.31 — Generate a `_redirects` file aliasing case + extension
 * variants of each per-site report's canonical URL. Netlify is
 * case-sensitive when serving static files (and doesn't normalise
 * extension-less paths in all cases when password-protected), so a
 * URL like `/r3-20260511-172410z` (lowercase `z`) misses the actual
 * file at `/r3-20260511-172410Z.html`. The redirects make every
 * predictable variant resolve cleanly:
 *
 *   /<base-lowercase-z>          → /<base>.html
 *   /<base-lowercase-z>.html     → /<base>.html
 *   /<base>                      → /<base>.html (no .html in URL)
 *
 * Three rules per per-site report; 17 sites → ~51 rules. The
 * `_redirects` file format is read by Netlify automatically at deploy
 * time from the publish root.
 *
 * @param {Array<{ htmlFile: string }>} siteResults — entries with htmlFile
 *   like "r3-20260511-172410Z.html"
 * @returns {string}
 */
export function generateNetlifyRedirects(siteResults) {
  const lines = [
    "# Auto-generated by filecap web-rollup — DO NOT EDIT.",
    "# Aliases case + extension variants of each per-site report so a",
    "# URL like `/r3-...z` (lowercase) or `/r3-...Z` (no .html) resolves",
    "# to the canonical `/r3-...Z.html` file. Helps when a manager",
    "# types a URL by hand or pastes from a tool that mangled casing.",
    "",
  ];
  for (const sr of siteResults) {
    const html = String(sr?.htmlFile ?? "");
    if (!html.endsWith(".html")) continue;
    const base = html.slice(0, -".html".length);
    if (!base) continue;
    const lower = base.toLowerCase();
    const canonical = `/${html}`;
    // Always emit the three aliases. Netlify deduplicates exact-match
    // rules and treats explicit destinations as authoritative.
    if (lower !== base) {
      lines.push(`/${lower}           ${canonical}   301`);
      lines.push(`/${lower}.html      ${canonical}   301`);
    }
    lines.push(`/${base}              ${canonical}   301`);
  }
  return lines.join("\n") + "\n";
}
