// v1.30.0 — shared sticky bottom bar, identical on every page of the
// web-rollup bundle (fleet index, /sites, /accessibility, per-site and
// by-type detail pages, orphaned-files page, file-errors page).
//
// Why sticky: the per-site detail pages end in tall HTML grids; with no
// always-visible chrome below them, a reader scrolling mid-page can't tell
// whether the grid continues past the fold or the page was cut off. A bar
// pinned to the viewport bottom (position: sticky; bottom: 0) is always in
// view while scrolling, then settles into normal document flow at the end of
// the page — so it never permanently covers the last rows of a grid and needs
// no body padding compensation. The body becomes a min-height:100vh flex
// column (main flex-grows) so the bar still pins to the viewport bottom on
// pages shorter than one screen.
//
// One source for markup + CSS so the bar cannot drift between pages. Pages
// with a light palette (orphaned-files) pass { theme: "light" }.

import { FILECAP_VERSION } from "../version.js";
import { escapeHtml as esc } from "../util/html.js";


/**
 * Render the shared footer bar.
 *
 * @param {object} [args]
 * @param {string} [args.generatedAt] - preformatted timestamp; omitted when empty
 * @returns {string} footer HTML
 */
export function renderSiteFooter({ generatedAt = "" } = {}) {
  return `<footer class="site-footer">
  <div class="site-footer-inner">
    <span class="site-footer-byline">Generated by the ICJIA Fleet Audit Assessment, v${esc(FILECAP_VERSION)}. For questions, contact <a href="mailto:christopher.schweda@illinois.gov">the audit administrator</a>.</span>
    ${generatedAt ? `<span class="site-footer-date">Generated ${esc(generatedAt)}</span>` : ""}
    <span class="site-footer-links">
      <a href="index.html">Home</a>
      <span aria-hidden="true">&middot;</span>
      <a href="help.html">Start here</a>
      <span aria-hidden="true">&middot;</span>
      <a href="sites.html">Sites</a>
      <span aria-hidden="true">&middot;</span>
      <a href="accessibility.html">Accessibility</a>
      <span aria-hidden="true">&middot;</span>
      <a href="search.html">Search</a>
      <span aria-hidden="true">&middot;</span>
      <a href="whats-new.html">What's New</a>
      <span aria-hidden="true">&middot;</span>
      <a href="https://github.com/ICJIA/icjia-fleet-audit" target="_blank" rel="noopener noreferrer">Source on GitHub</a>
      <span aria-hidden="true">&middot;</span>
      <a href="https://github.com/ICJIA/icjia-fleet-audit/blob/main/CHANGELOG.md" target="_blank" rel="noopener noreferrer">CHANGELOG</a>
    </span>
  </div>
</footer>`;
}

/**
 * CSS for the shared footer bar. Append AFTER the page's own stylesheet so
 * these rules win ties. Pages whose body has horizontal padding (the detail
 * pages) should additionally pull the bar full-bleed with negative side
 * margins matching that padding.
 *
 * @param {object} [args]
 * @param {"dark"|"light"} [args.theme]
 * @returns {string} CSS
 */
export function siteFooterCss({ theme = "dark" } = {}) {
  const c = theme === "light"
    ? { bg: "#f7f7f7", border: "#d9d9d9", text: "#555555", link: "#0066cc", linkHover: "#004a99" }
    : { bg: "#0d1117", border: "#21262d", text: "#9aa5b1", link: "#60a5fa", linkHover: "#93c5fd" };
  return `
/* ── skip link (v1.40.0, WCAG 2.4.1) ─────────────────────────
   First focusable element on every page; visually hidden until keyboard
   focus, then a high-contrast pill pinned to the top-left. */
.skip-link {
  position: absolute;
  left: -9999px;
  top: 0;
  z-index: 200;
  padding: 0.6rem 1rem;
  background: #1f6feb;
  color: #ffffff;
  font-weight: 700;
  border-radius: 0 0 8px 0;
  text-decoration: underline;
}
.skip-link:focus { left: 0; }

/* ── shared sticky bottom bar ───────────────────────────────── */
body { min-height: 100vh; min-height: 100dvh; display: flex; flex-direction: column; }
body > main {
  flex: 1 0 auto;
  /* v1.40.0 — a column-flex item's min-width:auto lets one wide grid/table
     inflate the main element past a phone viewport (mobile browsers then
     expand the layout viewport and clip text). Pin it to the page width. */
  min-width: 0;
  width: 100%;
}
.site-footer {
  position: sticky;
  bottom: 0;
  z-index: 90;
  flex: none;
  margin-top: 2.5rem;
  background: ${c.bg};
  border-top: 1px solid ${c.border};
  padding: 0.7rem 2rem;
  font-size: 0.8rem;
  color: ${c.text};
}
.site-footer-inner {
  max-width: 1200px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.35rem 1.5rem;
  flex-wrap: wrap;
}
.site-footer a { color: ${c.link}; text-decoration: underline; }
.site-footer a:hover { color: ${c.linkHover}; }
.site-footer-links { display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap; }
.site-footer-links a { white-space: nowrap; }
@media (max-width: 700px) {
  /* Phones: a viewport-pinned bar costs ~9% of the screen and overlapped the
     hero on load (v1.40.0) — return it to normal document flow and keep it to
     one or two short lines of nav links. Desktop keeps the sticky rationale. */
  .site-footer { position: static; padding: 0.55rem 1rem; font-size: 0.75rem; }
  .site-footer-byline, .site-footer-date { display: none; }
}
@media print {
  body { display: block; min-height: 0; }
  .site-footer { position: static; background: #fff; color: #555; border-color: #ccc; }
  .site-footer a { color: #0066cc; }
}
`;
}
