// v1.30.0 — shared sticky bottom bar, identical on every page of the
// web-rollup bundle (fleet index, /sites, /accessibility, per-site and
// by-type detail pages, orphaned-files page, file-errors page).
//
// Why sticky: the per-site detail pages end in tall HTML grids; with no
// always-visible chrome below them, a reader scrolling mid-page can't tell
// whether the grid continues past the fold or the page was cut off. A bar
// pinned to the viewport bottom (position: sticky; bottom: 0) is always in
// view while scrolling, then settles into normal document flow at the end of
// the page — so it never permanently covers the last rows of a grid and needs
// no body padding compensation. The body becomes a min-height:100vh flex
// column (main flex-grows) so the bar still pins to the viewport bottom on
// pages shorter than one screen.
//
// One source for markup + CSS so the bar cannot drift between pages. Pages
// with a light palette (orphaned-files) pass { theme: "light" }.

import { FILECAP_VERSION } from "../version.js";

function esc(s) {
  if (s === null || s === undefined) return "";
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * Render the shared footer bar.
 *
 * @param {object} [args]
 * @param {string} [args.generatedAt] - preformatted timestamp; omitted when empty
 * @returns {string} footer HTML
 */
export function renderSiteFooter({ generatedAt = "" } = {}) {
  return `<footer class="site-footer">
  <div class="site-footer-inner">
    <span class="site-footer-byline">Generated by filecap v${esc(FILECAP_VERSION)}. For questions, contact the audit administrator.</span>
    ${generatedAt ? `<span class="site-footer-date">Generated ${esc(generatedAt)}</span>` : ""}
    <span class="site-footer-links">
      <a href="index.html">Home</a>
      <span aria-hidden="true">&middot;</span>
      <a href="sites.html">Sites</a>
      <span aria-hidden="true">&middot;</span>
      <a href="accessibility.html">Accessibility</a>
      <span aria-hidden="true">&middot;</span>
      <a href="https://github.com/ICJIA/filecap-cli" target="_blank" rel="noopener noreferrer">filecap on GitHub</a>
      <span aria-hidden="true">&middot;</span>
      <a href="https://github.com/ICJIA/filecap-cli/blob/main/CHANGELOG.md" target="_blank" rel="noopener noreferrer">CHANGELOG</a>
    </span>
  </div>
</footer>`;
}

/**
 * CSS for the shared footer bar. Append AFTER the page's own stylesheet so
 * these rules win ties. Pages whose body has horizontal padding (the detail
 * pages) should additionally pull the bar full-bleed with negative side
 * margins matching that padding.
 *
 * @param {object} [args]
 * @param {"dark"|"light"} [args.theme]
 * @returns {string} CSS
 */
export function siteFooterCss({ theme = "dark" } = {}) {
  const c = theme === "light"
    ? { bg: "#f7f7f7", border: "#d9d9d9", text: "#555555", link: "#0066cc", linkHover: "#004a99" }
    : { bg: "#0d1117", border: "#21262d", text: "#9aa5b1", link: "#60a5fa", linkHover: "#93c5fd" };
  return `
/* ── shared sticky bottom bar ───────────────────────────────── */
body { min-height: 100vh; min-height: 100dvh; display: flex; flex-direction: column; }
body > main { flex: 1 0 auto; }
.site-footer {
  position: sticky;
  bottom: 0;
  z-index: 90;
  flex: none;
  margin-top: 2.5rem;
  background: ${c.bg};
  border-top: 1px solid ${c.border};
  padding: 0.7rem 2rem;
  font-size: 0.8rem;
  color: ${c.text};
}
.site-footer-inner {
  max-width: 1200px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.35rem 1.5rem;
  flex-wrap: wrap;
}
.site-footer a { color: ${c.link}; text-decoration: underline; }
.site-footer a:hover { color: ${c.linkHover}; }
.site-footer-links { display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap; }
.site-footer-links a { white-space: nowrap; }
@media (max-width: 700px) {
  .site-footer { padding: 0.55rem 1rem; font-size: 0.75rem; }
  /* Phones: keep the pinned bar to one or two short lines — nav links only. */
  .site-footer-byline, .site-footer-date { display: none; }
}
@media print {
  body { display: block; min-height: 0; }
  .site-footer { position: static; background: #fff; color: #555; border-color: #ccc; }
  .site-footer a { color: #0066cc; }
}
`;
}
